export default {
  // general
  retry: 'Retry', all: 'All', save: 'Save', saved: 'Saved', submit: 'Submit', send: 'Send', edit: 'Edit', delete: 'Delete', add: 'Add', end: 'End', remove: 'Remove',
  prev: 'Previous', next: 'Next', see_all: 'See all', read_more: 'Read more', no_data: 'Nothing to show yet.', active: 'Active', status: 'Status', date: 'Date', type: 'Type',
  name: 'Name', mobile: 'Mobile number', email: 'Email', email_optional: 'Email (optional)', password: 'Password', password_hint: 'At least 8 characters', address: 'Address', city: 'City',
  pincode: 'PIN code', message: 'Message', title: 'Title', subtitle: 'Subtitle', amount: 'Amount', reason: 'Reason', action: 'Action', start: 'Start', expires: 'Expires', until: 'until',
  total: 'Total', verify: 'Verify', language: 'Language', joined: 'Joined', customer: 'Customer', seller: 'Seller', sellers: 'Sellers', customers: 'Customers', product: 'Product', products: 'Products',
  category: 'Category', categories: 'Categories', price: 'Price', stock: 'Stock', rating: 'Rating', method: 'Method', payment: 'Payment', ticket: 'Ticket', sent: 'Sent', months: 'months', days_left: 'days left',
  // nav
  'nav.home': 'Home', 'nav.browse': 'Browse', 'nav.cart': 'Cart', 'nav.orders': 'Orders', 'nav.profile': 'Profile',
  search: 'Search', search_placeholder: 'Search fireworks…', notifications: 'Notifications', profile: 'Profile', wishlist: 'Wishlist', wishlist_empty: 'Your wishlist is empty.',
  // auth
  login: 'Login', register: 'Register', logout: 'Logout', logout_all: 'Log out of all devices', email_or_mobile: 'Email or mobile number', no_account: 'New here?', have_account: 'Already registered?',
  become_seller: 'Sell on MAVRIX FIRE', mobile_not_verified: 'Your mobile number is not verified yet. Verify it to place orders.', send_otp: 'Send OTP', otp_sent: 'OTP sent to your mobile.', mobile_verified: 'Mobile number verified.', otp_code: 'Authenticator code',
  // home
  hero_title: 'Sivakasi fireworks, from trusted shops', hero_sub: 'Compare verified sellers, pay securely with UPI and celebrate safely.', shop_now: 'Shop now', featured_shops: 'Featured shops', trending: 'Trending fireworks', popular: 'Popular products',
  new_arrivals: 'New arrivals', offers: 'Special offers', verified_shops: 'Verified shops', empty_home: 'Shops are getting ready. Please check back soon.', empty_products: 'No products found.', empty_shops: 'No shops yet.',
  shops: 'Shops', sort: 'Sort', in_stock_only: 'In stock only', 'sort.popular': 'Popular', 'sort.new': 'Newest', 'sort.price_asc': 'Price: low to high', 'sort.price_desc': 'Price: high to low', 'sort.rating': 'Top rated',
  // product / shop
  verified: 'Verified', out_of_stock: 'Out of Stock', in_stock: 'In stock', only_left: 'only {n} left', pack: 'Pack', description: 'Description', add_to_cart: 'Add to cart', buy_now: 'Buy now', added_to_cart: 'Added to cart',
  visit_shop: 'Visit shop', compare_sellers: 'Compare with other sellers', pickup_available: 'Shop pickup available', delivery_where_permitted: 'Seller delivery where legally permitted', delivery_not_offered: 'This seller offers pickup only',
  reviews: 'Reviews', review: 'Review', no_reviews: 'No reviews yet.', report: 'Report', reported: 'Reported. Thank you.', about_shop: 'About the shop', review_text: 'Your review (optional)', review_thanks: 'Thank you for your review!',
  // cart / checkout
  cart_empty: 'Your cart is empty.', cart_has_unavailable: 'Some items are unavailable. Please remove them to continue.', multi_seller_note: 'Items from different sellers are fulfilled as separate orders.', checkout: 'Checkout',
  fulfilment: 'Receive by', pickup: 'Pickup from shop', seller_delivery: 'Seller delivery', contact_address: 'Contact & address', age_confirm: 'I confirm that I am {n} years or older.',
  safety_confirm: 'I have read the fireworks safety instructions and will use fireworks only as permitted by law.', pay_now: 'Pay with UPI', retry_payment: 'Retry payment', upi_only_note: 'Online payment only (UPI / GPay). Cash on delivery is not available.',
  payment_success: 'Payment successful', payment_cancelled: 'Payment was cancelled. You can try again.', payment_pending_msg: 'Payment for this order is pending. Complete it to confirm your order.',
  // orders
  no_orders: 'No orders yet.', orders: 'Orders', order_id: 'Order ID', order_total: 'Order total', cancel_order: 'Cancel order', cancel_refund: 'Cancel & refund', confirm_cancel: 'Cancel this order? Your payment will be refunded.',
  order_cancelled_refund: 'Order cancelled. Refund initiated.', ready_for_pickup: 'Your order is ready for pickup', need_help: 'Need help with this order?',
  // support
  customer_care: 'Customer Care', new_ticket: 'New request', support_intro: 'Contact MAVRIX FIRE support about orders, payments, delivery or refunds.', no_tickets: 'No support requests yet.', issue_category: 'Issue category',
  attach_image: 'Attach image (optional)', message_sent: 'Message sent', draft_kept: 'your message is kept, please retry', type_message: 'Type a message…',
  'support.cat.order': 'Order Problem', 'support.cat.payment': 'Payment Problem', 'support.cat.product': 'Product Problem', 'support.cat.delivery': 'Delivery/Pickup Problem', 'support.cat.refund': 'Refund/Cancel Problem', 'support.cat.seller': 'Seller Problem', 'support.cat.other': 'Other',
  // safety
  safety_title: 'Fireworks safety & legal information', safety_short: 'Fireworks are dangerous. Use only as permitted by Indian and Tamil Nadu law, with adult supervision.',
  safety_1: 'Fireworks may be purchased only by adults (18+). Keep them away from children.', safety_2: 'Use only in open areas, away from buildings, vehicles, dry grass and crowds.', safety_3: 'Follow the instructions printed on each pack and light one item at a time.',
  safety_4: 'Keep a bucket of water or sand nearby. Never relight a dud; soak it in water.', safety_5: 'Do not carry or store fireworks in vehicles or homes beyond what the law allows.', safety_6: 'Observe local restrictions on permitted hours, places and types of fireworks.', safety_7: 'Delivery of fireworks is offered only by sellers permitted by MAVRIX FIRE, and only where legally allowed. Otherwise collect from the shop.',
  legal_note: 'MAVRIX FIRE operates within applicable Indian and Tamil Nadu laws. Sellers are responsible for compliance, and products or sellers may be removed or suspended for non-compliance.',
  // profile
  seller_dashboard: 'Seller dashboard',
  // seller
  seller_register: 'Seller registration', seller_register_note: 'Your application will be reviewed by MAVRIX FIRE before your shop goes live.', shop_name: 'Shop name', owner_name: 'Owner / business name', shop_address: 'Shop address', business_info: 'Business information',
  shop_photos: 'Shop photos', shop_logo: 'Shop logo', seller_fee_note: 'Seller plan: ₹199 for 6 months, payable after approval. Platform commission: 5% per successful order, deducted automatically. Bank details are collected securely by our payment partner, not in this app.',
  submit_application: 'Submit application', application_received: 'Application received. You can add photos now.', skip_for_now: 'Skip for now',
  'seller.nav.dashboard': 'Dashboard', 'seller.nav.products': 'Products', 'seller.nav.orders': 'Orders', 'seller.nav.offers': 'Offers', 'seller.nav.reviews': 'Reviews', 'seller.nav.settlements': 'Settlements', 'seller.nav.subscription': 'Subscription', 'seller.nav.shop': 'Shop profile',
  shop_live: 'Shop is live', shop_not_live: 'Not live yet', seller_pending_note: 'Your application is under review.', subscription_needed: 'Activate your seller plan to go live.', payout_account_pending: 'Payout account setup is pending with MAVRIX FIRE. You can sell once it is linked.',
  subscription_expiring_soon: 'Your seller plan expires in {days} days. Renew to stay live.', new_orders: 'New orders', gross_sales: 'Gross sales', platform_commission: 'Platform commission', your_earnings: 'Your earnings', pending_payout: 'Pending payout', sales_30d: 'Sales, last 30 days', top_products: 'Top products',
  add_product: 'Add product', edit_product: 'Edit product', no_products_yet: 'No products yet.', product_name: 'Product name', discount_price: 'Discount price', pack_quantity: 'Pack quantity', safety_notes: 'Safety notes', product_photos: 'Product photos', available: 'Available for sale',
  moderation_note: 'New products and content changes are reviewed by MAVRIX FIRE before they appear to customers.', product_submitted: 'Product submitted for review', confirm_delete: 'Delete this product?', commission: 'Commission',
  offer_title: 'Offer title', percent_off: 'Percent off', ends_at: 'Ends at', create_offer: 'Create offer', no_offers: 'No offers.', settlement_note: 'Customer payments are split automatically: 5% commission to MAVRIX FIRE, the rest to you. Funds are released after delivery or pickup.', settlement_status: 'Settlement',
  seller_plan: 'Seller plan', no_subscription: 'No subscription yet.', renew: 'Renew', pay_subscription: 'Pay ₹199 for 6 months', subscription_after_approval: 'Available after your shop is approved.',
  // admin
  admin_login: 'Admin login', admin_password: 'App Admin Password', admin_password_hint: 'At least 12 characters with upper, lower, number and symbol', confirm_password: 'Confirm password', first_admin_setup: 'First Admin Setup', setup_note: 'One-time setup. After the admin account is created this page is permanently disabled.',
  setup_token: 'Setup token', setup_token_hint: 'The ADMIN_SETUP_TOKEN set on the server at deployment', never_gmail_password: 'This is a new App Admin Password for MAVRIX FIRE. Never enter your Gmail password.', create_admin: 'Create admin account', setup_unavailable: 'First admin setup is not available.',
  'admin.nav.dashboard': 'Dashboard', 'admin.nav.sellers': 'Sellers', 'admin.nav.customers': 'Customers', 'admin.nav.products': 'Products', 'admin.nav.categories': 'Categories', 'admin.nav.orders': 'Orders', 'admin.nav.finance': 'Payments & Finance',
  'admin.nav.support': 'Customer Support', 'admin.nav.reviews': 'Reviews', 'admin.nav.marketing': 'Offers & Banners', 'admin.nav.notifications': 'Notifications', 'admin.nav.audit': 'Audit Logs', 'admin.nav.settings': 'Settings',
  'admin.stat.customers': 'Total customers', 'admin.stat.sellers': 'Total sellers', 'admin.stat.active_sellers': 'Active sellers', 'admin.stat.products': 'Total products', 'admin.stat.orders': 'Total orders', 'admin.stat.successful_orders': 'Successful orders', 'admin.stat.total_sales': 'Total sales',
  'admin.stat.platform_commission': 'Platform commission', 'admin.stat.seller_settlements': 'Seller settlements', 'admin.stat.pending_settlements': 'Pending settlements', 'admin.stat.subscription_revenue': 'Subscription revenue', 'admin.stat.open_tickets': 'Open support tickets', 'admin.stat.resolved_tickets': 'Resolved support tickets',
  'finance.payments': 'Payments', 'finance.commissions': 'Commission', 'finance.subscriptions': 'Seller subscriptions', 'finance.settlements': 'Seller settlements', 'finance.refunds': 'Refunds',
  'act.approve': 'Approve', 'act.reject': 'Reject', 'act.request_update': 'Request update', 'act.suspend': 'Suspend', 'act.block': 'Block', 'act.unblock': 'Unblock', 'act.remove': 'Remove', 'act.restore': 'Restore', 'act.hide': 'Hide', 'act.show': 'Show', 'act.disable': 'Disable',
  note_required: 'Enter a note for the seller', seller_details: 'Seller details', seller_settlements: 'Seller settlements', payout_account: 'Payout account (split settlement)', not_linked: 'Not linked yet', create_linked_account: 'Create linked account', delivery_permitted_toggle: 'Seller delivery permitted (compliance)',
  sort_order: 'Sort order', refund_reason: 'Reason for cancellation / refund', renewed: 'Renewed', reports: 'Reports', banner: 'Banner', broadcast: 'Broadcast notification', confirm_broadcast: 'Send this notification to everyone in the selected group?',
  settings_note: 'Changes apply to future orders only. Existing orders keep the commission they were created with.', commission_percent: 'Commission (%)', subscription_fee: 'Seller subscription fee', subscription_months: 'Subscription months', min_age: 'Minimum age', allowed_cities: 'Allowed cities (comma separated)',
  setup_2fa: 'Set up 2FA', tfa_scan: 'Add this secret to your authenticator app, then enter the 6-digit code.',
  // statuses
  'status.pending': 'Pending', 'status.approved': 'Approved', 'status.rejected': 'Rejected', 'status.update_required': 'Update required', 'status.suspended': 'Suspended', 'status.placed': 'Order placed', 'status.accepted': 'Seller accepted', 'status.preparing': 'Preparing',
  'status.ready': 'Ready', 'status.dispatched': 'Dispatched', 'status.out_for_delivery': 'Out for delivery', 'status.delivered': 'Delivered', 'status.completed': 'Completed', 'status.cancelled': 'Cancelled', 'status.pending_payment': 'Payment pending', 'status.paid': 'Paid',
  'status.open': 'Open', 'status.resolved': 'Resolved', 'status.active': 'Active', 'status.blocked': 'Blocked', 'status.expired': 'Expired', 'status.held': 'Held until delivery', 'status.released': 'Released', 'status.settled': 'Settled', 'status.reversed': 'Reversed',
  'status.failed': 'Failed', 'status.created': 'Created', 'status.initiated': 'Initiated', 'status.processed': 'Processed', 'status.removed': 'Removed', 'status.visible': 'Visible', 'status.refunded': 'Refunded', 'status.ended': 'Ended', 'status.disabled': 'Disabled',
  // errors
  'err.server_error': 'Something went wrong. Please try again.', 'err.network_error': 'Network problem. Check your connection and retry.', 'err.unauthenticated': 'Please log in to continue.', 'err.forbidden': 'You do not have permission for this.', 'err.not_found': 'Not found.',
  'err.invalid_credentials': 'Incorrect login details.', 'err.already_registered': 'This mobile number or email is already registered.', 'err.validation_error': 'Please check the details you entered.', 'err.rate_limited': 'Too many attempts. Please wait and try again.', 'err.csrf': 'Request blocked. Reload the page.',
  'err.mobile_not_verified': 'Please verify your mobile number first (Profile).', 'err.age_and_safety_required': 'Please confirm age and safety instructions.', 'err.product_unavailable': 'A product in your cart is no longer available.', 'err.out_of_stock': 'A product is out of stock.',
  'err.seller_not_ready_for_payments': 'This seller cannot accept payments yet.', 'err.delivery_not_permitted': 'Delivery is not permitted for this seller. Choose pickup.', 'err.delivery_area_not_permitted': 'Delivery is not permitted to this area. Choose pickup.', 'err.pickup_not_available': 'Pickup is not available for this seller.',
  'err.order_not_payable': 'This order can no longer be paid.', 'err.invalid_status_transition': 'That status change is not allowed.', 'err.cannot_cancel_now': 'The order can no longer be cancelled.', 'err.no_paid_payment': 'No paid payment found for this order.', 'err.review_not_allowed': 'You can review only completed purchases.', 'err.already_reviewed': 'You already reviewed this product.',
  'err.invalid_signature': 'Payment verification failed.', 'err.amount_mismatch': 'Payment amount mismatch. Support has been alerted.', 'err.payments_not_configured': 'Online payments are not configured yet.', 'err.payment_provider_error': 'The payment provider returned an error. Please retry.', 'err.payment_failed': 'Payment failed. You can retry.',
  'err.shop_not_approved': 'Your shop must be approved first.', 'err.shop_locked': 'Your shop cannot be edited right now.', 'err.shop_not_approved_yet': 'Available after approval.', 'err.invalid_image': 'This file is not a valid image.', 'err.invalid_image_size': 'Image is too large (max 8 MB).', 'err.image_required': 'Choose an image.', 'err.too_large': 'Request too large.',
  'err.otp_invalid': 'Invalid or expired code.', 'err.sms_not_configured': 'SMS is not configured yet.', 'err.invalid_setup_token': 'Invalid setup token.', 'err.setup_token_not_configured': 'Setup token is not configured on the server.', 'err.passwords_do_not_match': 'Passwords do not match.', 'err.password_too_short': 'Password is too short.', 'err.password_too_weak': 'Password needs upper, lower, number and symbol.', 'err.password_contains_email': 'Password must not contain your email name.',
  'err.note_required': 'A note is required.', 'err.already_onboarded': 'Already linked.', 'err.slug_exists': 'This slug already exists.', 'err.offer_end_in_past': 'End time must be in the future.', 'err.shop_not_found': 'Shop not found.',
  // notifications
  'notif.payment_success': 'Payment received for order {orderNo}.', 'notif.order_placed': 'Order {orderNo} placed.', 'notif.order_accepted': 'Seller accepted order {orderNo}.', 'notif.order_preparing': 'Order {orderNo} is being prepared.', 'notif.order_ready': 'Order {orderNo} is ready.',
  'notif.order_dispatched': 'Order {orderNo} has been dispatched.', 'notif.order_out_for_delivery': 'Order {orderNo} is out for delivery.', 'notif.order_delivered': 'Order {orderNo} is complete. Rate your purchase!', 'notif.order_cancelled': 'Order {orderNo} was cancelled. Refund initiated.',
  'notif.support_reply': 'MAVRIX FIRE replied to your request {ticketNo}.', 'notif.offer_broadcast': 'New offer', 'notif.admin_message': 'Message from MAVRIX FIRE', 'notif.seller_new_order': 'New order {orderNo}.', 'notif.stock_alert': 'Low stock: {stock} left.',
  'notif.subscription_active': 'Your seller plan is active.', 'notif.subscription_expiring': 'Your seller plan expires in {days} days.', 'notif.seller_approved': 'Your shop was approved. Activate your plan to go live.', 'notif.seller_rejected': 'Your application was rejected. {note}', 'notif.seller_update_required': 'Please update your application. {note}',
  'notif.seller_suspended': 'Your shop was suspended. {note}', 'notif.new_order': 'New order {orderNo}.', 'notif.seller_registered': 'Seller application: {shop}.', 'notif.support_new': 'New support message {ticketNo} ({category}).', 'notif.payment_issue': 'Payment issue: {reason}.', 'notif.subscription_event': 'Subscription {event}: {shop}.',
  no_notifications: 'No notifications.',
};
